spring.application.name=com

spring.datasource.url=jdbc:h2:mem:observaacao
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=XvKXEGSAKtuwkcUUveGErv8jiA5AyztXm8raUdoez1F
app.jwt.expiration-ms=86400000